version: '3.8'
services:




  db:
    image: postgres:alpine
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    env_file: .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_ready']
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  db_data: